vim.keymap("n", "<leader>rtc", function() require('jdtls').test_class() end, {desc = "Test Class"})
vim.keymap("n", "<leader>rt",  function() require('jdtls').test_nearest_method() end, {desc = "Test Nearest Method"})
vim.keymap({'n', 'v'},'<leader>oi', function() require('jdtls').organize_imports() end, {desc = "Organize Imports"})
vim.keymap({"n", "v"},"<leader>ec", function() require('jdtls').extract_constant() end, {desc = "Extract Constant"})
vim.keymap({'n', 'v'},'<leader>ev', function() require('jdtls').extract_variable() end, {desc = "Extract variable"})
vim.keymap({"n", "v"},"<leader>em", function() require('jdtls').extract_method()   end, {desc = "Extract Method"})
